version: 2.1
jobs:
  check:
    docker:
      - image: cimg/openjdk:8.0.282-browsers
    steps:
      - run:
          name: Check JAVA
          command: |
            echo 'Check JAVA Version'
            java -version
      - run:
          name: Check Unzip
          command: |
            echo 'Check Unzip'
            unzip -v
      - run:
          name: Checking hostname
          command: |
            hostname
            df
            id
            
  install:
    docker:
      - image: cimg/openjdk:8.0.282-browsers
    steps:
      - checkout
      - run:
          name: List File
          command: |
            echo 'List all files'
            pwd
            ls -al
      - run:
          name: Create folder
          command: |
            echo 'Create folder for aapi'
            mkdir -p /opt/symphony/agent
      - run:
          name: Unzip AAPI Image
          command: |
            echo 'Unzip AAPI'
            unzip ./agentapi/agent-2.62.2.zip -d /home/symphony/agent
            ls -al /home/symphony/agent
workflows:
  version: 2
  deploy:
    jobs:
      - check
