version: 2.1
jobs:
  check:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - run:
          name: Check JAVA
          command: |
            echo 'Check JAVA Version'
            java -version
      - run:
          name: Check Unzip
          command: |
            echo 'Check Unzip'
            unzip -v
      - run:
          name: Checking hostname
          command: |
            hostname
            
  install:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run:
          name: List File
          command: |
            echo 'List all files'
            ls -al
workflows:          
  version: 2
  deploy:
    jobs:
      - check