#test

version: 2.1
jobs:
  build:
    machine: true
    working_directory: ~/my_app
    parameters:
      jck_file:
        type: string
    steps:
      - checkout
      - run:
          name: List File
          command: |
            echo 'List all files'
            pwd
            ls -al ~/my_app
      - run:
          name: Download KeyManager Docker
          command: |
            docker volume create symphony_config
            docker volume create symphony_logs
            docker login docker.symphony.com -u symphony -p '$i64'
            docker run -d --name key-manger_20.12.2 -p 8443:8443 -p 8444:8444 -v symphony_config:/opt/symphony/config -v symphony_logs:/opt/symphony/logs -e TZ=Japan docker.symphony.com/symphony/key-manager:20.12.2
      - run:
          name: Setup Directories
          command: |
            docker stop $(docker ps -a | grep 20.12.2 | awk '{print $1}')
            docker logs $(docker ps -a | grep 20.12.2 | awk '{print $1}')
            docker volume ls
            sudo su -
            ls -l /var/lib/docker/volumes/symphony_config/_data
            ls -l /var/lib/docker/volumes/symphony_logs/_data
      - run:
          name: Setup Configuration Files
          command: |
            cp /home/circleci/my_app/keymanager/<< parameters.jck_file >> /var/lib/docker/volumes/symphony_config/_data/customer.jck
            cp /home/circleci/my_app/keymanager/keymanager_config.json /var/lib/docker/volumes/symphony_config/_data/keymanager_config.json
            cp /home/circleci/my_app/keymanager/keymanager.properties /var/lib/docker/volumes/symphony_config/_data/keymanager.properties
            cp /home/circleci/my_app/keymanager/environment.sh /var/lib/docker/volumes/symphony_config/_data/environment.sh
            cp /home/circleci/my_app/keymanager/keystore /var/lib/docker/volumes/symphony_config/_data/keystore
            cp /home/circleci/my_app/keymanager/truststore /var/lib/docker/volumes/symphony_config/_data/tomcat.truststore
            docker volume ls
            sudo su -
            ls -l /var/lib/docker/volumes/symphony_config/_data
            ls -l /var/lib/docker/volumes/symphony_logs/_data 

workflows:
  version: 2
  deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - docker
          jck_file: isid-na-prod-chat-glb-1-hsm.jck
